/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * User API
 * Type-safe API with auto-generated OpenAPI specification
 * OpenAPI spec version: 1.0.0
 */

export type PostUsers400 = {
  /** Error type */
  error: string;
  /** Error message */
  message: string;
};
